package com.micky.commonproj.domain.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CHANNEL_ITEM".
 */
public class ChannelItem {

    private Long id;
    private Integer cId;
    private String name;
    private Integer orderId;
    private Integer selected;
    private String urlHead;
    private String urlKey;
    private String urlEnd;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ChannelItem() {
    }

    public ChannelItem(Long id) {
        this.id = id;
    }

    public ChannelItem(Integer cId, String name, Integer orderId, Integer selected, String urlHead, String urlKey, String urlEnd) {
        this.cId = cId;
        this.name = name;
        this.orderId = orderId;
        this.selected = selected;
        this.urlHead = urlHead;
        this.urlKey = urlKey;
        this.urlEnd = urlEnd;
    }

    public ChannelItem(Long id, Integer cId, String name, Integer orderId, Integer selected, String urlHead, String urlKey, String urlEnd) {
        this.id = id;
        this.cId = cId;
        this.name = name;
        this.orderId = orderId;
        this.selected = selected;
        this.urlHead = urlHead;
        this.urlKey = urlKey;
        this.urlEnd = urlEnd;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCId() {
        return cId;
    }

    public void setCId(Integer cId) {
        this.cId = cId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getOrderId() {
        return orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public Integer getSelected() {
        return selected;
    }

    public void setSelected(Integer selected) {
        this.selected = selected;
    }

    public String getUrlHead() {
        return urlHead;
    }

    public void setUrlHead(String urlHead) {
        this.urlHead = urlHead;
    }

    public String getUrlKey() {
        return urlKey;
    }

    public void setUrlKey(String urlKey) {
        this.urlKey = urlKey;
    }

    public String getUrlEnd() {
        return urlEnd;
    }

    public void setUrlEnd(String urlEnd) {
        this.urlEnd = urlEnd;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
